/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.79
 * Generated at: 2023-09-01 03:07:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.Board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Board_005fList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("file:/C:/apache-tomcat-9.0.79/lib/jstl-1.2.jar", Long.valueOf(1692858145305L));
    _jspx_dependants.put("/WEB-INF/Board/../../../header.jsp", Long.valueOf(1693536355710L));
    _jspx_dependants.put("jar:file:/C:/apache-tomcat-9.0.79/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/apache-tomcat-9.0.79/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/BoardList.css\">\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>SMT 게시판</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/default.css\">\r\n");
      out.write("<link href='https://fonts.googleapis.com/css?family=Roboto:500,900,100,300,700,400' rel='stylesheet' type='text/css'>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script> \r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<h1 class=\"second\"><span>SMT</span></h1>\r\n");
      out.write("<section id=\"navSection\">\r\n");
      out.write("<div>\r\n");
      out.write("  <nav class=\"blend\">\r\n");
      out.write("    <ul>\r\n");
      out.write("      <li><a href=\"#\">Home</a></li>\r\n");
      out.write("      <li><a href=\"boardPage\">문의/답변</a></li>\r\n");
      out.write("      <li><a href=\"#\">ABOUT</a></li>\r\n");
      out.write("      <li><a href=\"#\">AAA</a></li>\r\n");
      out.write("      <li><a href=\"#\">SETTING</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("  </nav>\r\n");
      out.write("</div>  \r\n");
      out.write("</section>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section class=\"board\">\r\n");
      out.write("	<form>	\r\n");
      out.write("		<div class=\"searchBox\">\r\n");
      out.write("				<select class=\"custom-select\" id=\"condition\" name=\"condition\">\r\n");
      out.write("					<option value=\"title\">제목</option>\r\n");
      out.write("					<option value=\"contents\">내용</option>\r\n");
      out.write("				</select>\r\n");
      out.write("				<input type=\"text\" id=\"searchKeyword\" class=\"form-control\" name=\"searchKeyword\" maxlength=\"20\">\r\n");
      out.write("				<button type=\"button\" class=\"btn\" onClick=\"getQuesList()\">검색</button>\r\n");
      out.write("		</div>\r\n");
      out.write("	</form>\r\n");
      out.write("		\r\n");
      out.write("<div id = \"boardListDiv\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id = \"pageBtns\">\r\n");
      out.write("</div>\r\n");
      out.write("</section>\r\n");
      out.write("<script src=\"js/board.js\"></script>	\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("	getQuesList();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("document.addEventListener(\"keydown\", function(event) {\r\n");
      out.write("    if (event.key === \"Enter\") {\r\n");
      out.write("    	event.preventDefault(); // 폼 제출 방지\r\n");
      out.write("        getQuesList(); // Enter 키 누르면 함수 호출\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function getQuesList(nNum){ //페이징 + 리스트 \r\n");
      out.write("	var condition = $(\"#condition\").val();\r\n");
      out.write("	var searchKeyword = $(\"#searchKeyword\").val();\r\n");
      out.write("	var nowNum = 0;\r\n");
      out.write("	if(nNum != null){\r\n");
      out.write("		nowNum = nNum;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	$.ajax({\r\n");
      out.write("	    type: \"POST\",\r\n");
      out.write("	    url: \"goBoard\", \r\n");
      out.write("	    data: {\r\n");
      out.write("	    	\"condition\" : condition,\r\n");
      out.write("	    	\"searchKeyword\" : searchKeyword,\r\n");
      out.write("	    	\"nowNum\" : nowNum\r\n");
      out.write("	    },\r\n");
      out.write("	   /*  processData: false,\r\n");
      out.write("	    contentType: false, */\r\n");
      out.write("	    success: function(data) {\r\n");
      out.write("	    	var bList = data.list;\r\n");
      out.write("	    	var pageInfo = data.pageInfo;\r\n");
      out.write("	    	var comment_html = \"\";\r\n");
      out.write("	    	var pageBtn_html = \"\";\r\n");
      out.write("	    	\r\n");
      out.write("	    	if(Array.isArray(bList) && bList.length > 0){\r\n");
      out.write("				comment_html = \"<table class='board-table'>\";\r\n");
      out.write("				comment_html += \"<thead>\";\r\n");
      out.write("				comment_html += \"<tr>\";\r\n");
      out.write("				comment_html += \"<th scope='col' class='th-num'>번호</th>\";\r\n");
      out.write("				comment_html += \"<th scope='col' class='th-title'>제목</th>\";\r\n");
      out.write("				comment_html += \"<th scope='col' class='th-writer'>작성자</th>\";\r\n");
      out.write("				comment_html += \"<th scope='col' class='th-date'>등록일</th>\";\r\n");
      out.write("				comment_html += \"</tr>\";\r\n");
      out.write("				comment_html += \"</thead>\";\r\n");
      out.write("				comment_html += \"<tr>\";\r\n");
      out.write("				comment_html += \"<tbody>\";\r\n");
      out.write("				\r\n");
      out.write("				for(i = 0;i < bList.length;i++){\r\n");
      out.write("					var board_ID = bList[i].board_ID;\r\n");
      out.write("					var comment_ID = bList[i].comment_ID;\r\n");
      out.write("					var title = bList[i].title;\r\n");
      out.write("					var ins_Date_Time = bList[i].ins_Date_Time;\r\n");
      out.write("					\r\n");
      out.write("					comment_html += \"<tr OnClick='BoardInfo(\"+ board_ID + \")' class='boardList'>\";\r\n");
      out.write("					comment_html += \"<td>\" + board_ID + \"</td>\";\r\n");
      out.write("					comment_html += \"<td>\" + title + \"</td>\";\r\n");
      out.write("					comment_html += \"<td>\" + comment_ID + \"</td>\";\r\n");
      out.write("					comment_html += \"<td>\" + ins_Date_Time + \"</td>\";\r\n");
      out.write("					comment_html += \"</tr>\";\r\n");
      out.write("					\r\n");
      out.write("					}\r\n");
      out.write("				\r\n");
      out.write("					comment_html += \"</tbody>\";\r\n");
      out.write("					comment_html += \"</table>\";\r\n");
      out.write("					comment_html += \"<div class='insBtnBox'>\";\r\n");
      out.write("					comment_html += \"<button class='btn BoardMenuBtn' onClick='insertBoard()'>\";\r\n");
      out.write("					comment_html += \"<svg xmlns='http://www.w3.org/2000/svg' width='16' height='16' fill='currentColor' class='bi bi-pencil-fill' viewBox='0 0 16 16'>\";\r\n");
      out.write("					comment_html += \"<path d='M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z'/>\";\r\n");
      out.write("					comment_html += \"</svg>\";\r\n");
      out.write("					comment_html += \"</button>\";\r\n");
      out.write("					comment_html += \"</div>\";\r\n");
      out.write("					\r\n");
      out.write("					if(pageInfo.listNum != 0){\r\n");
      out.write("			    		\r\n");
      out.write("			    		if(!(pageInfo.nowNum == 1 || pageInfo.endNum == 1)){\r\n");
      out.write("				    		pageBtn_html += \"<a onClick='getQuesList(1)' class='pBtn'>&lt;&lt;</a>\";\r\n");
      out.write("				    		pageBtn_html += \"<a class='pBtn' onClick='getQuesList(\" + (pageInfo.nowNum - 1) + \")'>이전</a>\";\r\n");
      out.write("			    		}\r\n");
      out.write("\r\n");
      out.write("			    		for (i = pageInfo.startNum; i <= pageInfo.endNum; i++) {\r\n");
      out.write("			    			if(i == pageInfo.nowNum){\r\n");
      out.write("				    		    pageBtn_html += \"<button class='pBtn pNumBtn selectedNumBtn' onClick='getQuesList(\" + i + \")'>\" + i + \"</button>\";\r\n");
      out.write("			    			}else{\r\n");
      out.write("				    		    pageBtn_html += \"<button class='pBtn pNumBtn' onClick='getQuesList(\" + i + \")'>\" + i + \"</button>\";\r\n");
      out.write("			    			}\r\n");
      out.write("			    		}\r\n");
      out.write("\r\n");
      out.write("			    		if(!(pageInfo.nowNum == pageInfo.totalNum || pageInfo.endNum == 1)){\r\n");
      out.write("				    		pageBtn_html += \"<a class='pBtn' onClick='getQuesList(\" + (pageInfo.nowNum + 1) + \")'>다음</a>\";\r\n");
      out.write("				    		pageBtn_html += \"<a class='pBtn' onClick='getQuesList(\" + pageInfo.totalNum + \")'>&gt;&gt;</a>\";\r\n");
      out.write("			    		}\r\n");
      out.write("			    	}\r\n");
      out.write("\r\n");
      out.write("	    }else{\r\n");
      out.write("			comment_html += \"등록된 결과가 없습니다.\";  	\r\n");
      out.write("			comment_html += \"\";    	\r\n");
      out.write("	    }\r\n");
      out.write("					$(\"#boardListDiv\").html(comment_html);\r\n");
      out.write("			    	$(\"#pageBtns\").html(pageBtn_html);\r\n");
      out.write("    },\r\n");
      out.write("	    error: function(xhr, status, error) {\r\n");
      out.write("	      alert(\"목록을 불러오는 중 에러가 발생했습니다.\");\r\n");
      out.write("	    }\r\n");
      out.write("	  });\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
