/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.79
 * Generated at: 2023-09-01 07:56:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.Board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class Board_005fInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("file:/C:/apache-tomcat-9.0.79/lib/jstl-1.2.jar", Long.valueOf(1692858145305L));
    _jspx_dependants.put("/WEB-INF/Board/../../../header.jsp", Long.valueOf(1693536355710L));
    _jspx_dependants.put("jar:file:/C:/apache-tomcat-9.0.79/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/apache-tomcat-9.0.79/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/BoardList.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/BoardInfo.css\">\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>SMT 게시판</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/default.css\">\r\n");
      out.write("<link href='https://fonts.googleapis.com/css?family=Roboto:500,900,100,300,700,400' rel='stylesheet' type='text/css'>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script> \r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<h1 class=\"second\"><span>SMT</span></h1>\r\n");
      out.write("<section id=\"navSection\">\r\n");
      out.write("<div>\r\n");
      out.write("  <nav class=\"blend\">\r\n");
      out.write("    <ul>\r\n");
      out.write("      <li><a href=\"#\">Home</a></li>\r\n");
      out.write("      <li><a href=\"boardPage\">문의/답변</a></li>\r\n");
      out.write("      <li><a href=\"#\">ABOUT</a></li>\r\n");
      out.write("      <li><a href=\"#\">AAA</a></li>\r\n");
      out.write("      <li><a href=\"#\">SETTING</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("  </nav>\r\n");
      out.write("</div>  \r\n");
      out.write("</section>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<section class=\"board\">\r\n");
      out.write("\r\n");
      out.write("<h2 class=\"boardInfoTitle\"><span>상세보기</span></h2>\r\n");
      out.write("\r\n");
      out.write("<div id=\"boardModiDelBtnBox\">\r\n");
      out.write("	<button type=\"button\" class=\"btn BoardMenuBtn\" onClick=\"updateFrm(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.board_ID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")\">\r\n");
      out.write("		<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-pencil-square\" viewBox=\"0 0 16 16\">\r\n");
      out.write("		  <path d=\"M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z\"/>\r\n");
      out.write("		  <path fill-rule=\"evenodd\" d=\"M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z\"/>\r\n");
      out.write("		</svg>\r\n");
      out.write("		수정\r\n");
      out.write("	</button>\r\n");
      out.write("	<button type=\"button\" class=\"btn BoardMenuBtn\" onClick=\"deleteBoard(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.board_ID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")\">\r\n");
      out.write("		<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-trash\" viewBox=\"0 0 16 16\">\r\n");
      out.write("		  <path d=\"M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6Z\"/>\r\n");
      out.write("		  <path d=\"M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1ZM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118ZM2.5 3h11V2h-11v1Z\"/>\r\n");
      out.write("		</svg>\r\n");
      out.write("		삭제\r\n");
      out.write("	</button>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"boardInfoBox\">\r\n");
      out.write("	<input type=\"text\" id=\"boardTitle\" name=\"title\" class=\"form-control\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\r\n");
      out.write("\r\n");
      out.write("	");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	<p>\r\n");
      out.write("	");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.contents}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("	</p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<hr> \r\n");
      out.write("<p id=\"AnsInsBoxTitle\">댓글</p>\r\n");
      out.write("<div id=\"AnsInsBox\">\r\n");
      out.write("	<form id=\"frm\" enctype=\"multipart/form-data\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-10\">\r\n");
      out.write("				<input type=\"hidden\" id=\"board_ID\" name=\"board_ID\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.board_ID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\r\n");
      out.write("				<input type=\"hidden\" id=\"comment_ID\" name=\"comment_ID\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.comment_ID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\r\n");
      out.write("				<input type=\"text\" id=\"answerID\" class=\"form-control\" placeholder=\"작성자\" maxLength=10>\r\n");
      out.write("				<hr>\r\n");
      out.write("				<textarea id=\"ansContents\" name=\"ansContent\" class=\"form-control\" rows=\"3\" placeholder=\"댓글을 입력해주세요\" maxLength=500></textarea>\r\n");
      out.write("				<div id=\"fileLabelBox\">\r\n");
      out.write("					<label for=\"imageInput\">\r\n");
      out.write("						<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"25\" height=\"25\" fill=\"#21252978\" class=\"bi bi-paperclip\" viewBox=\"0 0 16 16\">\r\n");
      out.write("						  <path d=\"M4.5 3a2.5 2.5 0 0 1 5 0v9a1.5 1.5 0 0 1-3 0V5a.5.5 0 0 1 1 0v7a.5.5 0 0 0 1 0V3a1.5 1.5 0 1 0-3 0v9a2.5 2.5 0 0 0 5 0V5a.5.5 0 0 1 1 0v7a3.5 3.5 0 1 1-7 0V3z\"/>\r\n");
      out.write("						</svg>\r\n");
      out.write("					</label>\r\n");
      out.write("					<p id=\"originName\" style=\"display : inline-block; color: #21252978; font-size:0.8rem; margin-right:10px;\"></p>\r\n");
      out.write("					<img id=\"previewImg\" style=\"max-height:50px; width:auto;\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<input type=\"file\" id=\"imageInput\" name=\"file_Name\" onChange=\"previewImage(event)\" accept=\"image/*\" style=\"display:none;\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-2\">\r\n");
      out.write("				<button type=\"button\" class=\"btn\" id=\"insAnsBtn\" onClick=\"insAns(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.board_ID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")\">등록</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"comment_Box\"> <!-- 댓글이 들어갈 박스 -->\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</section>\r\n");
      out.write("<script src=\"js/board.js\"></script>	\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("	getAnsList();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function previewImage(event) {\r\n");
      out.write("  var input = event.target;\r\n");
      out.write("  if (input.files && input.files[0]) {\r\n");
      out.write("    var reader = new FileReader();\r\n");
      out.write("\r\n");
      out.write("    reader.onload = function(e) {\r\n");
      out.write("      var previewElement = document.getElementById('previewImg');\r\n");
      out.write("      previewElement.src = e.target.result;\r\n");
      out.write("    };\r\n");
      out.write("\r\n");
      out.write("    reader.readAsDataURL(input.files[0]);\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("	\r\n");
      out.write("function deleteBoard(boardID){\r\n");
      out.write("	var board_ID = boardID;\r\n");
      out.write("	if(confirm(\"해당 문의를 삭제하시겠습니까?\")){\r\n");
      out.write("		$.ajax({\r\n");
      out.write("		    type: \"POST\",\r\n");
      out.write("		    url: \"deleteBoard\", \r\n");
      out.write("		    data: {\r\n");
      out.write("		    	\"board_ID\" : board_ID\r\n");
      out.write("		    },\r\n");
      out.write("		    success: function(data) {\r\n");
      out.write("		    	if(data.result == \"suc\"){\r\n");
      out.write("		    		alert(\"삭제가 완료되었습니다.\");\r\n");
      out.write("		    		location.href = \"boardPage\";\r\n");
      out.write("		    	}else{\r\n");
      out.write("		    		alert(\"오류가 발생했습니다. 잠시 후 다시 시도해주세요.\");\r\n");
      out.write("		    		return;\r\n");
      out.write("		    	}\r\n");
      out.write("		    },\r\n");
      out.write("		    error: function(xhr, status, error) {\r\n");
      out.write("		      alert(\"에러가 발생했습니다.\");\r\n");
      out.write("		    }\r\n");
      out.write("		  });\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function insAns(board_ID) {\r\n");
      out.write("	  var answerID = $(\"#answerID\").val();\r\n");
      out.write("	  var ansContents = $(\"#ansContents\").val();\r\n");
      out.write("	  var fileInput = $(\"#imageInput\")[0];\r\n");
      out.write("	  var file = fileInput.files[0];\r\n");
      out.write("      var commentID = $(\"#comment_ID\").val();\r\n");
      out.write("	  \r\n");
      out.write("      if(answerID == \"\"){\r\n");
      out.write("    	  alert(\"댓글 작성자를 작성해주세요.\");\r\n");
      out.write("    	  $(\"#answerID\").focus();\r\n");
      out.write("    	  return;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      if(ansContents == \"\"){\r\n");
      out.write("    	  alert(\"내용을 작성해주세요.\");\r\n");
      out.write("    	  $(\"#ansContents\").focus();\r\n");
      out.write("    	  return;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("	  var formData = new FormData();\r\n");
      out.write("	  formData.append(\"board_ID\", board_ID);\r\n");
      out.write("	  formData.append(\"comment_ID\",commentID);\r\n");
      out.write("	  formData.append(\"answerID\", answerID);\r\n");
      out.write("	  formData.append(\"ansContents\", ansContents);\r\n");
      out.write("	  if (file) {\r\n");
      out.write("	    formData.append(\"fileNm\", file);\r\n");
      out.write("	  }\r\n");
      out.write("\r\n");
      out.write("	  $.ajax({\r\n");
      out.write("	    type: \"POST\",\r\n");
      out.write("	    url: \"insAns\", \r\n");
      out.write("	    data: formData,\r\n");
      out.write("	    processData: false,\r\n");
      out.write("	    contentType: false,\r\n");
      out.write("	    success: function(response) {\r\n");
      out.write("	    	getAnsList();\r\n");
      out.write("	    	var previewElement = document.getElementById('previewImg');\r\n");
      out.write("	        previewElement.src = ''; // src를 비우는 부분\r\n");
      out.write("	    	frm.reset();\r\n");
      out.write("	    	\r\n");
      out.write("	    },\r\n");
      out.write("	    error: function(xhr, status, error) {\r\n");
      out.write("	      alert(\"댓글 등록 실패\");\r\n");
      out.write("	    }\r\n");
      out.write("	  });\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("function getAnsList() {\r\n");
      out.write("	\r\n");
      out.write("	const board_ID = $(\"#board_ID\").val();\r\n");
      out.write("	const answer_ID = $(\"#answerID\").val();\r\n");
      out.write("	\r\n");
      out.write("	var formData = new FormData();\r\n");
      out.write("    formData.append(\"board_ID\", board_ID);\r\n");
      out.write("    \r\n");
      out.write("    $.ajax({\r\n");
      out.write("		type: \"POST\",\r\n");
      out.write("	    url: \"listAns\",\r\n");
      out.write("	    data: formData,\r\n");
      out.write("	    processData: false,\r\n");
      out.write("	    contentType: false,\r\n");
      out.write("	    success: function(data) {\r\n");
      out.write("			if(Array.isArray(data) && data.length > 0){\r\n");
      out.write("				var list = data;\r\n");
      out.write("				\r\n");
      out.write("				var comment_html = \"<div>\";\r\n");
      out.write("				\r\n");
      out.write("				for(i = 0;i < list.length;i++){\r\n");
      out.write("					var content = list[i].Contents;\r\n");
      out.write("					var writer = list[i].anser_ID;\r\n");
      out.write("					var ins_Date_Time = list[i].ins_Date_Time;\r\n");
      out.write("					var file_ViewName = list[i].file_ViewName;\r\n");
      out.write("					comment_html += \"<div>\";\r\n");
      out.write("					comment_html += \"<form enctype='multipart/form-data'>\" //폼시작\r\n");
      out.write("					comment_html += \"<input type='hidden' class='board_ID form-control' name='board_ID' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.board_ID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'>\";\r\n");
      out.write("					comment_html += \"<div class='ansWriterDate'>\";\r\n");
      out.write("					comment_html += \"<input type='text' class='answerID form-control' value='\" + writer + \"' style='display:block;' readonly>\";\r\n");
      out.write("					comment_html += \"<input type='text' class='insDateTime form-control' value='\" + ins_Date_Time + \"' style='display:block;' readonly>\";\r\n");
      out.write("					comment_html += \"</div>\";\r\n");
      out.write("					\r\n");
      out.write("					if(file_ViewName != null){\r\n");
      out.write("						comment_html += \"<div style='text-align:right;'><a class='downloadLink' href='downloadImg?file_Name=\" + file_ViewName + \"&board_ID=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.board_ID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&reply=1'>[첨부파일]</a></div>\"; \r\n");
      out.write("						comment_html += \"<img id='ansImge' src='data:image/png;base64,\"+ file_ViewName + \"' alt='Image'><br>\";\r\n");
      out.write("					}\r\n");
      out.write("					\r\n");
      out.write("					comment_html += \"<textarea class='Anscontent form-control' readonly>\" + content + \"</textarea>\";\r\n");
      out.write("					\r\n");
      out.write("					comment_html += \"<div class='ansUpdfileLabelBox' style='display:none;'>\";\r\n");
      out.write("					comment_html += \"<label for='ansUpdimageInput\" + i +\"'>\";\r\n");
      out.write("					comment_html += \"<svg xmlns='http://www.w3.org/2000/svg' width='25' height='25' fill='#21252978' class='bi bi-paperclip' viewBox='0 0 16 16'>\";\r\n");
      out.write("					comment_html += \"<path d='M4.5 3a2.5 2.5 0 0 1 5 0v9a1.5 1.5 0 0 1-3 0V5a.5.5 0 0 1 1 0v7a.5.5 0 0 0 1 0V3a1.5 1.5 0 1 0-3 0v9a2.5 2.5 0 0 0 5 0V5a.5.5 0 0 1 1 0v7a3.5 3.5 0 1 1-7 0V3z'/>\";\r\n");
      out.write("					comment_html += \"</svg>\";\r\n");
      out.write("					comment_html += \"</label>\";\r\n");
      out.write("					comment_html += \"<img class='ansUpdpreviewImg' style='max-height:50px; width:auto;'>\";\r\n");
      out.write("					comment_html += \"<input type='file' id='ansUpdimageInput\" + i + \"' class='fileNm' name='file_Name' accept='image/*' style='display:none;'>\";\r\n");
      out.write("					comment_html += \"</div>\";\r\n");
      out.write("					comment_html += \"<div class='ansUpdDBCancle' style='display:none;'>\";\r\n");
      out.write("					comment_html += \"<button type='button' class='btn updDBBtn'>등록</button>\";\r\n");
      out.write("					comment_html += \"<span class='btnLine' style='display:inline-block!important;'>|</span>\"\r\n");
      out.write("					comment_html += \"<button type='button' class='btn updDelBtn'>취소</button>\";\r\n");
      out.write("					comment_html += \"</div>\";\r\n");
      out.write("					comment_html += \"</form>\"; //폼끝\r\n");
      out.write("\r\n");
      out.write("					\r\n");
      out.write("					comment_html += \"<div class='ansUpdDelBtn'>\"\r\n");
      out.write("					comment_html += \"<button type='button' class='btn updBtn'>수정</button>\";\r\n");
      out.write("					comment_html += \"<span class='btnLine1'>|</span>\"\r\n");
      out.write("					comment_html += \"<button type='button' class='btn delBtn'>삭제</button><br></div>\";\r\n");
      out.write("					comment_html += \"</div>\"\r\n");
      out.write("					comment_html += \"<hr class='ansHr'>\";\r\n");
      out.write("					}\r\n");
      out.write("				\r\n");
      out.write("					comment_html += \"</div>\";\r\n");
      out.write("					\r\n");
      out.write("					$(\".comment_Box\").html(comment_html);\r\n");
      out.write("					\r\n");
      out.write("					// 수정/삭제 버튼 클릭 이벤트 핸들러\r\n");
      out.write("					$(\".updBtn\").click(function() {//수정\r\n");
      out.write("					    var $container = $(this).closest(\"div\").parent();\r\n");
      out.write("					    var $textarea = $container.find(\".Anscontent\");//textarea\r\n");
      out.write("					    var $saveBtn = $container.find(\".updDBBtn\");//수정완료버튼\r\n");
      out.write("					    var $delBtn = $container.find(\".delBtn\");//삭제버튼\r\n");
      out.write("					    var $btnLine = $container.find(\".btnLine\");//수정 삭제 구분선\r\n");
      out.write("					    var $updDelBtn = $container.find(\".updDelBtn\");//수정취소버튼\r\n");
      out.write("					    var $ansUpdDelBtn = $container.find(\".ansUpdDelBtn\");//수정취소버튼\r\n");
      out.write("					    var $ansUpdfileLabelBox = $container.find(\".ansUpdfileLabelBox\");//수정 파일 올릴 수 있는 div\r\n");
      out.write("					    var $ansUpdDBCancle = $container.find(\".ansUpdDBCancle\");//수정, 취소버튼 있는 div\r\n");
      out.write("					    \r\n");
      out.write("					    $ansUpdDelBtn.hide();\r\n");
      out.write("					    $textarea.prop(\"readonly\", false);\r\n");
      out.write("					    $textarea.focus();\r\n");
      out.write("					    /* $saveBtn.show();*/\r\n");
      out.write("					    $updDelBtn.show(); \r\n");
      out.write("					    $ansUpdfileLabelBox.show();\r\n");
      out.write("					    $ansUpdDBCancle.show();\r\n");
      out.write("					});\r\n");
      out.write("					\r\n");
      out.write("					$(\".updDelBtn\").click(function() {//수정취소\r\n");
      out.write("					    var $container = $(this).closest(\"div\").parent().parent();\r\n");
      out.write("					    var $textarea = $container.find(\".Anscontent\");//textarea\r\n");
      out.write("					    var $ansUpdDelBtn = $container.find(\".ansUpdDelBtn\");//수정|삭제 div\r\n");
      out.write("					    var $ansUpdfileLabelBox = $container.find(\".ansUpdfileLabelBox\");//수정 파일 올릴 수 있는 div\r\n");
      out.write("					    var $ansUpdDBCancle = $container.find(\".ansUpdDBCancle\");//수정, 취소버튼 있는 div\r\n");
      out.write("					    \r\n");
      out.write("					    $textarea.prop(\"readonly\", true);\r\n");
      out.write("					    /* $saveBtn.hide();\r\n");
      out.write("					    $(this).hide(); */\r\n");
      out.write("					    $ansUpdfileLabelBox.hide();\r\n");
      out.write("					    $ansUpdDBCancle.hide();\r\n");
      out.write("					    $ansUpdDelBtn.show();\r\n");
      out.write("					    \r\n");
      out.write("					    $textarea.val($textarea.prop(\"defaultValue\")); //초기값으로 돌리기\r\n");
      out.write("					});\r\n");
      out.write("					\r\n");
      out.write("					$(\".updDBBtn\").click(function() {//수정 DB입력\r\n");
      out.write("						if(confirm(\"정말 수정하시겠습니까?\")){\r\n");
      out.write("						    var $container = $(this).closest(\"div\").parent();\r\n");
      out.write("						    var $textarea = $container.find(\".Anscontent\");\r\n");
      out.write("						    \r\n");
      out.write("						    var boardID = $container.find(\".board_ID\").val();\r\n");
      out.write("						    var content = $textarea.val();\r\n");
      out.write("						    var fileInput = $container.find(\".fileNm\")[0];\r\n");
      out.write("						    var file = fileInput.files[0];\r\n");
      out.write("						    var answerID = $container.find(\".answerID\").val();\r\n");
      out.write("							  \r\n");
      out.write("						    var formData = new FormData();\r\n");
      out.write("						    formData.append(\"board_ID\", board_ID);\r\n");
      out.write("						    formData.append(\"answerID\", answerID);\r\n");
      out.write("						    formData.append(\"content\", content);\r\n");
      out.write("						    if (file) {\r\n");
      out.write("						      formData.append(\"fileNm\", file);\r\n");
      out.write("						    }\r\n");
      out.write("						    \r\n");
      out.write("						    $.ajax({\r\n");
      out.write("						        url: \"updAns\", \r\n");
      out.write("						        type: \"POST\",\r\n");
      out.write("						        data: formData,\r\n");
      out.write("						        processData: false,\r\n");
      out.write("							    contentType: false,\r\n");
      out.write("						        success: function(response) {\r\n");
      out.write("									alert(\"수정이 완료되었습니다.\");\r\n");
      out.write("									getAnsList();\r\n");
      out.write("						        },\r\n");
      out.write("						        error: function(xhr, status, error) {\r\n");
      out.write("						        	alert(\"수정에 실패하였습니다.\");\r\n");
      out.write("						        }\r\n");
      out.write("						    });\r\n");
      out.write("						}\r\n");
      out.write("					});\r\n");
      out.write("					\r\n");
      out.write("					$(\".delBtn\").click(function() {//삭제\r\n");
      out.write("						if(confirm(\"댓글을 삭제하시겠습니까?\\n 삭제 후 되돌릴 수 없습니다.\")){\r\n");
      out.write("						    var $container = $(this).closest(\"div\");\r\n");
      out.write("						    var $span = $container.find(\".answerID\");\r\n");
      out.write("						    var boardID = $(\"#board_ID\").val();\r\n");
      out.write("						    var answerID = writer;\r\n");
      out.write("						    \r\n");
      out.write("						    $.ajax({\r\n");
      out.write("						        type: \"POST\",\r\n");
      out.write("						        url: \"delAns\", \r\n");
      out.write("						        data: { \"board_ID\": boardID,\r\n");
      out.write("						        		\"answer_ID\": answerID }, \r\n");
      out.write("						        success: function(response) {\r\n");
      out.write("									alert(\"댓글이 삭제되었습니다.\");\r\n");
      out.write("									getAnsList();\r\n");
      out.write("						        },\r\n");
      out.write("						        error: function(xhr, status, error) {\r\n");
      out.write("						        	alert(\"댓글이 삭제가 실패하였습니다.\");\r\n");
      out.write("						        }\r\n");
      out.write("						    });\r\n");
      out.write("						}\r\n");
      out.write("					});\r\n");
      out.write("					\r\n");
      out.write("					$(\".fileNm\").change(function(event) {//댓글 수정에 사진 미리보기\r\n");
      out.write("						  var input = event.target;\r\n");
      out.write("						  var $container = $(this).closest(\"div\"); // 파일 입력 요소를 감싸는 가장 가까운 <div>\r\n");
      out.write("						  \r\n");
      out.write("						  if (input.files && input.files[0]) {\r\n");
      out.write("						    var reader = new FileReader();\r\n");
      out.write("\r\n");
      out.write("						    reader.onload = function(e) {\r\n");
      out.write("						      var $previewImg = $container.find(\".ansUpdpreviewImg\"); // 해당 위치의 미리보기 이미지 요소\r\n");
      out.write("						      $previewImg.attr(\"src\", e.target.result);\r\n");
      out.write("						    };\r\n");
      out.write("\r\n");
      out.write("						    reader.readAsDataURL(input.files[0]);\r\n");
      out.write("						  }\r\n");
      out.write("						});\r\n");
      out.write("				}\r\n");
      out.write("			else{\r\n");
      out.write("				var comment_html = \"<div>등록된 댓글이 없습니다.</div>\";\r\n");
      out.write("				$(\".comment_Box\").html(comment_html);\r\n");
      out.write("			}\r\n");
      out.write("	    }\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/Board/Board_Info.jsp(37,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.file_ViewName ne null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	<div>\r\n");
          out.write("		<a class=\"downloadLink\" href=\"downloadImg?file_Name=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.file_ViewName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&board_ID=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.board_ID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">[첨부파일]</a>\r\n");
          out.write("	</div>\r\n");
          out.write("		<img src=\"data:image/png;base64,");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.file_ViewName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" alt=\"Image\">\r\n");
          out.write("	");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
