/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.79
 * Generated at: 2023-08-30 08:11:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1692926617424L));
    _jspx_dependants.put("jar:file:/C:/Users/keroz/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/SMT/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <style>\r\n");
      out.write("      .bd-placeholder-img {\r\n");
      out.write("        font-size: 1.125rem;\r\n");
      out.write("        text-anchor: middle;\r\n");
      out.write("        -webkit-user-select: none;\r\n");
      out.write("        -moz-user-select: none;\r\n");
      out.write("        user-select: none;\r\n");
      out.write("      }\r\n");
      out.write(" \r\n");
      out.write("      @media (min-width: 768px) {\r\n");
      out.write("        .bd-placeholder-img-lg {\r\n");
      out.write("          font-size: 3.5rem;\r\n");
      out.write("        }\r\n");
      out.write("      }\r\n");
      out.write("      a {\r\n");
      out.write("          cursor: pointer;\r\n");
      out.write("      }\r\n");
      out.write("    </style>\r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        function changeView(value){\r\n");
      out.write("            \r\n");
      out.write("            if(value == \"0\") // HOME 버튼 클릭시 첫화면으로 이동\r\n");
      out.write("            {\r\n");
      out.write("                location.href=\"main.do\";\r\n");
      out.write("            }\r\n");
      out.write("            else if(value == \"1\") // 로그인 버튼 클릭시 로그인 화면으로 이동\r\n");
      out.write("            {\r\n");
      out.write("                location.href=\"LoginForm.do\";\r\n");
      out.write("            }\r\n");
      out.write("            else if(value == \"2\") // 회원가입 버튼 클릭시 회원가입 화면으로 이동\r\n");
      out.write("            {\r\n");
      out.write("                location.href=\"SignUpForm.do\";\r\n");
      out.write("            }\r\n");
      out.write("            else if(value == \"3\") // 회원정보 버튼 클릭시 회원정보 상세보기 화면으로 이동\r\n");
      out.write("            {\r\n");
      out.write("                location.href=\"PwdCheckForm.do\";\r\n");
      out.write("            }\r\n");
      out.write("            else if(value == \"4\") // 로그아웃 버튼 클릭시 로그아웃 처리\r\n");
      out.write("            {\r\n");
      out.write("                location.href=\"MemberLogoutAction.do\";\r\n");
      out.write("            }\r\n");
      out.write("            else if(value == \"5\") // 보드 버튼 클릭시 보드 게시판 화면으로 이동\r\n");
      out.write("            {\r\n");
      out.write("                location.href=\"BoardListAction.bo\";\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write(" \r\n");
      out.write("    <link href=\"css/navbar-top-fixed.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- CSS FILES -->\r\n");
      out.write("    <!-- CSS FILES -->        \r\n");
      out.write("        <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("        \r\n");
      out.write("        <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css2?family=Montserrat:wght@500;600;700&family=Open+Sans&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("                        \r\n");
      out.write("        <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("        <link href=\"css/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("        <link href=\"css/templatemo-topic-listing.css\" rel=\"stylesheet\">    \r\n");
      out.write("        <!--\r\n");
      out.write("TemplateMo 590 topic listing\r\n");
      out.write("https://templatemo.com/tm-590-topic-listing\r\n");
      out.write("        -->\r\n");
      out.write("      </head>\r\n");
      out.write("      <body>\r\n");
      out.write("        <nav class=\"navbar navbar-expand-lg\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <a class=\"navbar-brand\" href=\"BoardListForm.bo\">\r\n");
      out.write("                        <!-- <i class=\"bi-back\"></i> -->\r\n");
      out.write("                        <span>게시판</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"d-lg-none ms-auto me-4\">\r\n");
      out.write("                        <a href=\"#top\" class=\"navbar-icon bi-person smoothscroll\"></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("    \r\n");
      out.write("                    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                        <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("                    </button>\r\n");
      out.write("    \r\n");
      out.write("                    <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("                        <ul class=\"navbar-nav ms-lg-5 me-lg-auto\">\r\n");
      out.write("                            <li class=\"nav-item\">\r\n");
      out.write("                                <a class=\"nav-link click-scroll\" href=\"#section_1\">Home</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("\r\n");
      out.write("                            <li class=\"nav-item\">\r\n");
      out.write("                                <a class=\"nav-link click-scroll\" href=\"#section_2\">Browse Topics</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("    \r\n");
      out.write("                            <li class=\"nav-item\">\r\n");
      out.write("                                <a class=\"nav-link click-scroll\" href=\"#section_3\">How it works</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("\r\n");
      out.write("                            <li class=\"nav-item\">\r\n");
      out.write("                                <a class=\"nav-link click-scroll\" href=\"#section_4\">FAQs</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("    \r\n");
      out.write("                            <li class=\"nav-item\">\r\n");
      out.write("                                <a class=\"nav-link click-scroll\" href=\"#section_5\">Contact</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("\r\n");
      out.write("                            <li class=\"nav-item dropdown\">\r\n");
      out.write("                                <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarLightDropdownMenuLink\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">Pages</a>\r\n");
      out.write("\r\n");
      out.write("                                <ul class=\"dropdown-menu dropdown-menu-light\" aria-labelledby=\"navbarLightDropdownMenuLink\">\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"topics-listing.html\">Topics Listing</a></li>\r\n");
      out.write("\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"contact.html\">Contact Form</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"d-none d-lg-block\">\r\n");
      out.write("                            <a href=\"#top\" class=\"navbar-icon bi-person smoothscroll\"></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </nav>\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("            <section class=\"hero-section d-flex justify-content-center align-items-center\" id=\"section_1\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-lg-8 col-12 mx-auto\">\r\n");
      out.write("                            <h1 class=\"text-white text-center\">Search and Write Down Your Question</h1>\r\n");
      out.write("\r\n");
      out.write("                            <h6 class=\"text-center\">Ask Anything</h6>\r\n");
      out.write("\r\n");
      out.write("                            <form method=\"get\" class=\"custom-form mt-4 pt-2 mb-lg-0 mb-5\" role=\"search\">\r\n");
      out.write("                                <div class=\"input-group input-group-lg\">\r\n");
      out.write("                                    <span class=\"input-group-text bi-search\" id=\"basic-addon1\">\r\n");
      out.write("                                        \r\n");
      out.write("                                    </span>\r\n");
      out.write("\r\n");
      out.write("                                    <input name=\"keyword\" type=\"search\" class=\"form-control\" id=\"keyword\" placeholder=\"SMTVIsion\" aria-label=\"Search\">\r\n");
      out.write("\r\n");
      out.write("                                    <button type=\"submit\" class=\"form-control\">Search</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </section>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
